# Generated by Django 2.2.8 on 2021-08-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
