# Generated by Django 2.2.8 on 2021-08-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_auto_20210816_1805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coffee',
            new_name='Donate',
        ),
    ]
